### ISSUE TITLE
Check Contao 4.2-Compatibility

### ISSUE THREAD

**Issue by ADoebeling** [1601com/contao-urlcleaner#1]
http://stackoverflow.com/questions/12229970/use-composer-without-packagist

**Comment by Xendiadyon** [comment]
https://getcomposer.org/doc/articles/versions.md

**Comment by Xendiadyon** [comment]
Da keine Bundle.php existiert, kann es auf diesem Weg nicht installiert werden:
https://www.marcosimbuerger.ch/contao-kurzanleitungen-details/erweiterung-in-contao-4-mit-composer-installieren.html

**Comment by Xendiadyon** [comment]
manuelle Installation hat funktioniert

**Comment by ADoebeling** [comment]
@Xendiadyon Das heißt wir löschen diesem Fork einfach wieder?

**Comment by Xendiadyon** [comment]
jain.
Du würdest mir einen großen Gefallen tun, wenn du in deiner Community rumfragst, wie man eine Erweiterung, die man geforkt und per Composer installiert hat (das kann ich jetzt!) in Contao installiert, wenn keine "Bundle.php" Datei existiert. Wir wollen ja immer noch alte Erweiterungen zu Contao4 kompatibel machen und per Pull-Request updaten.

Aktuell würde ich das so machen, dass ich den Ordner in vendor auf system/modules symlinke und dann mit Contaos nativer "manueller Integration alter Erweiterungen" in der AppKernel.php einbinde:
`new ContaoModuleBundle('urlcleaner', $this->getRootDir()),`

das wäre so, als hätte man die Erweiterung manuell in den Ordner hochgeladen, nur tausendmal umständlicher. Und da hat ein Pull-Request auch keinen Sinn, da ja die Bundle.php fehlt.

Die korrekte und übliche Art, das per Composer-Namespace einzubinden:
`new MadeYourDay\Contao\RockSolidCustomElementsBundle(),`
funktioniert nicht, weil eben die Bundle.php fehlt.

Haben deine Kollegen eine Idee, wie man das lösen kann und anschließend einen Pull-Request setzen kann? Selbst eine Bundle.php anlegen? Wo muss die liegen, was muss da drinstehen?

**Comment by Xendiadyon** [comment]
https://www.marcosimbuerger.ch/contao-kurzanleitungen-details/erweiterung-in-contao-4-mit-composer-installieren.html

**Comment by Xendiadyon** [comment]
ich habe jetzt z.B. die Erweiterung https://github.com/Kuestenschmiede/con4gis_maps3 installiert, die Contao4-kompatibel ist. Dort existiert keine Bundle.php und ich habe keine Idee, wie ich an den korrekten Namespace komme...

**Comment by Xendiadyon** [comment]
tot
